# Generated by Django 3.2 on 2021-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('duration', models.IntegerField()),
                ('authername', models.CharField(max_length=30)),
            ],
        ),
    ]
