# Generated by Django 3.2 on 2021-07-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('stname', models.CharField(max_length=50)),
                ('stmarks', models.FloatField()),
                ('staddr', models.TextField(max_length=250)),
            ],
        ),
    ]
