# Generated by Django 3.2.5 on 2021-07-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rollno',
        ),
    ]
