# Generated by Django 3.2.5 on 2021-07-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeAuth', '0002_remove_student_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ataddr',
            new_name='staddr',
        ),
    ]
