# Generated by Django 3.2.5 on 2021-07-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeAuth', '0003_rename_ataddr_student_staddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
